auth_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import signup_process, login_process, dashboard, logout_process
from . import views

urlpatterns = [
    path('signup/', signup_process, name='signup_process'),
    path('login/', login_process, name='login_process'),
    path('dashboard/', dashboard, name='dashboard'),
    path('logout/', logout_process, name='logout_process'),
]

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('blog', views.blog_post_list_view, name='blog_post_list_view'),
    path('create/', views.blog_post_create_view, name='blog_post_create_view'),
    path('<int:id>/', views.blog_post_detail_view, name='blog_post_detail_view'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
    path('appointment/', include('appointment.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blog/blog_post_list.html
{% extends 'base.html' %}
{% if user.is_authenticated %}
          {% if user.doctor %}
            <a href="{% url 'blog:blog_post_create_view' %}" class="btn btn-primary mb-3">Post Blog</a>
          {% endif %}
        {% endif %}

{% block content %}

  <div class="row">
    {% for post in blog_posts %}
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title }}" width="200" height="200">

          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.content }}</p>
            
        </div>
            
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <img src="{{ post.image.url }}" alt="{{ post.title }}">
  <p>{{ post.content }}</p>
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Blog Post</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}