appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path('doctors/', views.doctor_list, name='doctor_list'),
    path('book-appointment/<int:doctor_id>/', views.book_appointment, name='book_appointment'),
    path('add_doctor/', views.add_doctor, name='add_doctor'),
    path('appointments-patients/', views.patient_appointments, name='patient_appointments'),
    path('appointments-doctors/', views.doctor_appointments, name='doctor_appointments'),
]

auth_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import signup_process, login_process, dashboard, logout_process
from . import views

urlpatterns = [
    path('signup/', signup_process, name='signup_process'),
    path('login/', login_process, name='login_process'),
    path('dashboard/', dashboard, name='dashboard'),
    path('logout/', logout_process, name='logout_process'),
]

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('blog', views.blog_post_list_view, name='blog_post_list_view'),
    path('create/', views.blog_post_create_view, name='blog_post_create_view'),
    path('<int:id>/', views.blog_post_detail_view, name='blog_post_detail_view'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls')),
    path('blog/', include('blog_app.urls', namespace='blog_app')),
    path('appointment/', include('appointment.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
          crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Blog App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}

            {% if request.session.user_role == 'Doctor' %}
           <li> <a class="btn btn-primary" href="{% url 'blog_app:blog_post_create_view' %}">Post Blog</a></li>
            <li><a href="{% url 'appointment:doctor_appointments' %}" class="btn btn-primary">View My Appointments</a></li>

            {% endif %}
            
            {% if request.session.user_role == 'Patient' %}
            <li><a href="{% url 'appointment:doctor_list' %}">Book Appointment</a></li>
            <li><a href="{% url 'appointment:patient_appointments' %}" class="btn btn-primary">View My Appointments</a></li>
        
        

            {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog_app:blog_post_list_view' %}">Read Blogs</a>
              </li>
            {% endif %}
            
        </ul>
        {% if can_add_doctor %}
    <a href="{% url 'appointment:add_doctor' %}" class="btn btn-primary">Add Doctor</a>
        {% endif %}
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard' %}">dashboard</a>
          </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout_process' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_process' %}">Login</a>

                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup_process' %}">signup</a>
              </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmIwMjAzQi7hSjvX2KsW"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
  <h1>Welcome to your dashboard</h1>
  {% if user_type %}
    <p>You are a {{ user_type }}</p>
    {% if details %}
    <img src="{{ details.profile_picture.url }}" alt="Profile Picture" style="width:200px;height:200px;">
      <p>Name: {{ details.first_name }} {{ details.last_name }}</p>
      <p>Email: {{ details.email }}</p>
      <p>Address: {{ details.address_line_1 }} {{details.pincode }}</p>
      {% if user_type == 'Patient' %}
        <!-- Display patient-specific details here -->
      {% elif user_type == 'Doctor' %}
        <!-- Display doctor-specific details here -->
      {% endif %}
    {% else %}
      <p>No details found for {{ user_type }}</p>
    {% endif %}
  {% else %}
    <p>No user type found</p>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <button type="submit" name="logout">Logout</button>
  </form>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  {% if messages %}
    {% for message in messages %}
      <div>{{ message }}</div>
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username"><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password"><br>
    <button type="submit">Login</button>
  </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>Signup</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Signup</button>
  </form>
{% endblock %}